namespace Oda {
    /// <summary>
    /// A where clause used in a SQL query generated by <see cref="Sql.JsonReadOrDelete(string,int,int,Oda.SqlWhere)"/>.
    /// </summary>
    /// <seealso cref="SqlParameter"/>
    /// <seealso cref="Sql.JsonReadOrDelete(string,int,int,Oda.SqlWhere)" />
    public class SqlWhere {
        private SqlParameter[] _parameters;
        private string _whereClause;
        /// <summary>
        /// Gets or sets the parmeters used in this condition.
        /// </summary>
        /// <value>
        /// The parmeters array.
        /// </value>
        public SqlParameter[] Parmeters {
            get { return _parameters ?? new SqlParameter[] { }; }
            set { _parameters = value; } 
        }
        /// <summary>
        /// Gets or sets the where clause.  For example: where UserAgent = @useragent.
        /// This value must contain the word "where" and be a valid where clause.
        /// </summary>
        /// <value>
        /// The where clause.
        /// </value>
        public string WhereClause {
            get { return _whereClause ?? string.Empty; }
            set { _whereClause = value; }
        }
        /// <summary>
        /// Initializes a new instance of the <see cref="SqlWhere"/> class.
        /// </summary>
        public SqlWhere(){}
        /// <summary>
        /// Initializes a new instance of the <see cref="SqlWhere"/> class.
        /// </summary>
        /// <param name="whereClause">The where clause.</param>
        /// <param name="parameters">The parameters.</param>
        public SqlWhere(string whereClause, SqlParameter[] parameters) {
            WhereClause = whereClause;
            Parmeters = parameters;
        }
    }
}
